# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Login to docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run docker image
        run:  |
          docker pull fortifydocker/fortify-ci-tools:4.0.1-jdk-11
          # docker run -d -p 9000:9000 sonarqube:9.9.5-community
          # sleep 15 &
          # curl -X POST -H "Authorization: Basic admin:admin" "http://localhost:9000/api/user_tokens/create?name=MyToken"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run:  ls

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          java -version
          javac testJava.java
          java testJava
         
