name: Deploy Vulnerable Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:

      - name: Run docker image
        run:  |
          docker pull bkimminich/juice-shop 
          docker run -d -p 127.0.0.1:3000:3000 bkimminich/juice-shop
          docker ps
          ifconfig

      - name: Perform ZAP full scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000/'
